# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
         
    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: '12'
      
    - run: npm ci
    - run: npm run build

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
          target_branch: master
          build_dir: public
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

